### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by dy**
Short changelog:
- Added `test` command in npm to `npm test`.
- Restricted list of exported files in npm module.
- Separated `set` and `get` methods for those who don’t need both, in order to be able to include only `require('caret-position/get')` (to minify build size).
- Fixed all jshint warnings.
- Added jsdoc annotations.
- Added wrapper providing both explicit and short API (if you mind, I can get back only explicit API).
- Added standalone build with browserify, as well as alias `npm run build`
- Added badges and icons to the readme

### CODE REVIEW

**Comment by dfcreative** [comment]
@marcuswestin what’s up?

**Comment by dfcreative** [comment]
@marcuswestin ping

**Comment by dfcreative** [comment]
@marcuswestin it’s been a while :)

**Comment by marcuswestin** [comment]
I really apologize for the delay. Life, you know. Sorry.

The underlying reason though is that while I really like part of the patch, and feel super appreciative of the work you put in to it, the patch includes too many things I don't really like.

c02f6a53d37 is relatively harmless, but it doesn't add anything either
f1157bfa16d doesn't say what it does and the diff includes literally every line of code. I'm also explicitly against splitting up into multiple files as it trades complexity for an insignificant code size reduction in a corner case and a code size addition for the typical use case.

I was expecting just what you said in #1, plain and simple, and if you had additional patches you wanted to make I'd have liked to have them in separate pull requests.

Sorry :( I know it comes across as annoying and perhaps ungrateful, it's not.

**Comment by dfcreative** [comment]
Ow, sorry, I probably should’ve better describe what I’ve done and why.

At first, I was keeping in mind during the refactoring to save current user experience, so that old users could take `caret-position.js` and don’t feel the difference. I believe it is done well.

But I supposed that as far you’ve published `caret-position` to npm and as far people who use npm use web-bundling tools like browserify, webpack etc., that you would like to adapt it’s behaviour and structure to npm modules conventions for the new audience. I strived to stick to these conventions looking for best-practices in [component](https://github.com/component), [web-modules](https://github.com/webmodules/), [substack repos](https://github.com/substack?tab=repositories) and others during the refactoring.

There are complications with current caret-position for npm users:
1. unable to control bundle size / functionality for final bundle, because of [low cohesion](http://en.wikipedia.org/wiki/Cohesion_(computer_science)).
2. the module is wrapped into environmental UMD wrapper, which is not related to logic of a project, and possibly in building pipeline causes some custom actions by unwrapping / handling that corner case, otherwise wrapped twice.

Why I decided to separate `set` from `get`? Because I used `set` in my projects, AFAIR, at least 4 times, when I just needed to set caret position to the last line when user clicks on text area. But I hardly can remember a case when I used `get`. Meanwhile `get` is times lengthen than `set`, and unavoidably inflates the bundle, which is bad.
Besides, `require('caret-position/get')` is really quite useful pattern for a scrupulous web-developer, allowing easily save extra-bytes, but there is still the ability to `require('caret-position').get`.

Also I’ve unwrapped the code from UMD, delegating it to browserify via `npm run build`, which is really [Separation of Concerns](http://en.wikipedia.org/wiki/Separation_of_concerns).

That’s unfortunate that you’ve found that a complication, because I really didn’t mean that, there's just separation and annotation. Probably it is because of a quite big pull-request, but I really don’t see anything bad in it.

**Comment by dy** [comment]
@marcuswestin Hello, Marcus!
I understand that you want to keep your project slim and concise.

But for now fork of this wonderful component has been taken by kudago company as it's officially supported component, and it's going to be further supported and developed by kudago team. https://github.com/kudago/Caret-position

It is probably going to be used by some community and well-supported.
We're seeking for an opportunity now to publish an npm package with this fork, but it'd be regretful if we publish this with different package name, other than `caret-position`, as it is very natural name.

So there's a question for you: would you prefer to keep main branch in npm and support it, or you could let us use this npm repo for our specific fork?

If you decide to leave this npm repo name to us, all you need to do is just 
`$ npm owner add dfcreative caret-position`

In any case, thank you for your consideration.

**Comment by marcuswestin** [comment]
Cool! Great to see you fork it in the direction that you want.

Thanks for letting me know!

Cheers,
Marcus

**Comment by dy** [comment]
Do I understand you right that you don't want us to maintain this project in npm?

**Comment by marcuswestin** [comment]
I don't feel very strongly one way or the other - why don't you create a new npm name? Should avoid any future confusion.

-- while mobile

**Comment by dy** [comment]
No confusion for devs but confusion for users. Just wanted to avoid extra enthropy of npm, as fork does technically the same as the original repo.

**Comment by dy** [comment]
@marcuswestin so no chance this fork is going to be merged?
Caret-position in npm now looks poor https://www.npmjs.com/package/caret-position. No good for npm users and npm policy...
Can you recap strong reasons against the fork?

**Comment by marcuswestin** [comment]
Hi,

I don't plan to merge. In my eyes it mostly adds complexity, and I always
try to keep it as low as possible.

Thanks for checking back in though, and apologies for all the delays in
this dialogue! Others things tend to take priority, and then it ends up
buried in the inbox.

Cheers, and thanks again,
Marcus

**Comment by dy** [comment]
Well at least that would be nice to add sort of readme to npm, unless it is personal package.

Cheers!

**Comment by marcuswestin** [comment]
I would definitely take a PR with readme info :)

**Pull request closed without merging**
